### ISSUE TITLE
Read psa on modrinth

### ISSUE THREAD

**Issue by thebikwirm** [sguest/jei-multiblocks#2]
does the issues mean recipes etc stuff not working in JEI

**Comment by thebikwirm** [comment]
this is 16.5

**Comment by sguest** [comment]
I'm not sure I follow your question, but the state of 1.16.5 is things should work just fine in singleplayer, but the mod really doesn't work at all in multiplayer.

**Comment by thebikwirm** [comment]
Does it effect jei at all or it's just the mod doesn't do anything
Having issues with immersive engineering recipes not showing in jei, and read the psa and trying to narrow down the problem, also has work fine in mp for ages, thanks

**Comment by sguest** [comment]
After establishing that the mod isn't going to work on a server in 1.16.5, I haven't spent too much time looking into exactly *what* breaks. If you're looking to narrow down an issue, I'd recommend uninstalling the mod to see what happens without it.
