### ISSUE TITLE
Complied 1.20.1 alpha does not support Neoforged

### ISSUE THREAD

**Issue by DaeTheDragon** [sguest/jei-multiblocks#5]
When launching, an incorrect forge version is reported if the user is running Neoforged instead of the old version of Forge Mod-Loader

**Comment by sguest** [comment]
There is no compiled version for 1.20, the latest version(s) of this mod are for 1.19.2 because 1.20 of IE introduced some incompatibilities that I haven't been able to figure out how to get past.
